eval_config:
  model_name_or_path: vidore/colpali-v1.1 # Model version used in modernvbert paper
  wrapper_cls: ColPaliWrapper
  tasks:
  - ViDoRe(v1)
  - ViDoRe(v2)
  batch_size: 32
  output_folder: results/
  encode_kwargs: {}
  framework: ["ColPali"]
  similarity_fn_name: "max_sim"