eval_config:
  model_name_or_path: jinaai/jina-embeddings-v4
  wrapper_cls: JinaV4Wrapper
  tasks:
  - ViDoRe(v1)
  - ViDoRe(v2)
  batch_size: 32
  output_folder: results/
  encode_kwargs: {}
  framework: ["Sentence Transformers", "PyTorch"]
  similarity_fn_name: "cosine"
  attn_implementation: "flash_attention_2"
  