eval_config:
  model_name_or_path: ModernVBERT/bimodernvbert
  wrapper_cls: BiModernVBertWrapper
  tasks:
  - ViDoRe(v1)
  - ViDoRe(v2)
  batch_size: 32
  output_folder: results/
  encode_kwargs: {}
  framework: ["ColPali"]
  similarity_fn_name: "MaxSim"
  attn_implementation: "flash_attention_2"