config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/colmodernvbert
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColModernVBertProcessor
    pretrained_model_name_or_path:  "ModernVBERT/modernvbert"

  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.ColModernVBert
    pretrained_model_name_or_path: "ModernVBERT/modernvbert"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
    trust_remote_code: true

  train_dataset: 
    (): colpali_engine.utils.dataset_transformation.load_train_set
  eval_dataset: !import ../data/test_data_hf.yaml

  # max_length: 50
  run_eval: true
  loss_func:
    (): colpali_engine.loss.late_interaction_losses.ColbertPairwiseCELoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 3
    per_device_train_batch_size: 32
    gradient_checkpointing: false
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    per_device_eval_batch_size: 8
    eval_strategy: "steps"
    dataloader_num_workers: 2
    save_steps: 500
    logging_steps: 5
    eval_steps: 100
    warmup_steps: 100
    learning_rate: 2e-4
    save_total_limit: 1
    resume_from_checkpoint: false
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "colqwen2"
    # run_name: "colqwen2-ba32-nolora"
    report_to: "wandb"
  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: gaussian
    bias: none
    task_type: FEATURE_EXTRACTION
    target_modules: (.*(model.text_model).*(Wo|Wqkv|Wi).*$|.*(custom_text_proj).*$)